import type {PortableTextBlock, ProductionContentSnapshot} from "./types";

const block = (key: string, text: string): PortableTextBlock => ({
  _type: "block",
  _key: key,
  children: [{_type: "span", _key: `${key}-span`, text}],
});

const portrait = {
  _id: "media-portrait",
  label: "Test portrait",
  alt: "Test-only portrait placeholder",
  source: "Test fixture",
  rightsStatus: "owned" as const,
  placements: ["portrait"],
  originalDimensions: {width: 1200, height: 1200},
  targetAspectRatio: "1:1",
  assetUrl: "https://cdn.sanity.io/images/foow59ov/production/test-portrait.webp",
};

const shareImage = {
  _id: "media-share",
  label: "Test share image",
  alt: "Test-only share image placeholder",
  source: "Test fixture",
  rightsStatus: "owned" as const,
  placements: ["default-share-image"],
  originalDimensions: {width: 1200, height: 630},
  targetAspectRatio: "1200:630",
  assetUrl: "https://cdn.sanity.io/images/foow59ov/production/test-share.webp",
};

export const productionContentFixture: ProductionContentSnapshot = {
  siteSettings: {
    _id: "siteSettings",
    siteTitle: "Test Portfolio",
    siteDescription: "Test-only production content fixture.",
    canonicalUrl: "https://example.com",
    socialName: "Test Portfolio",
    allowIndexing: false,
    defaultShareImage: shareImage,
  },
  profile: {
    _id: "profile",
    name: "测试用户",
    englishName: "Test Person",
    professionalTitle: "Test Professional",
    locations: ["Test City"],
    timezone: "America/New_York",
    availability: "Available for test work",
    shortBio: "Short test biography.",
    fullBio: [block("profile", "Full test biography.")],
    portrait,
  },
  homepage: {
    _id: "homepage",
    heroTitleLines: ["Test", "Professional"],
    heroNameLines: ["Test", "Person"],
    heroTechChips: ["Next.js", "TypeScript", "UI systems"],
    regionLabel: "Test Region",
    valuePropositionLines: ["Test value", "Test outcome"],
    availability: "Available for test work",
    primaryCtaLabel: "Contact Test Person",
    aboutTitle: "个人介绍",
    aboutLabel: "About",
    about: [block("about", "Test about content.")],
    marqueePrimaryLines: ["Test", "Service"],
    marqueeSecondaryLines: ["Test", "Focus"],
    skillTickerItems: ["Test skill"],
    experienceTitle: "工作经历",
    experienceLabel: "Experience",
    experienceIntro: "Test experience introduction.",
    projectsTitle: "项目经历",
    projectsLabel: "Project",
    projectsIntro: "Test projects introduction.",
    testimonialsTitle: "Test Testimonials",
    testimonialsIntro: "Test Testimonials introduction.",
    contactTitleLines: ["Test", "Contact"],
    contactInvitation: "Test contact invitation.",
  },
  educations: [0, 1].map((order) => ({
    _id: `education-${order}`,
    institution: `Test Institution ${order + 1}`,
    degree: "Test Degree",
    fieldOfStudy: "Test Field",
    location: "Test City",
    startDate: `202${order}-09`,
    endDate: `202${order + 1}-06`,
    isExpected: order === 1,
    description: "Test education description.",
    highlights: ["Test education highlight"],
    relatedUrl: "https://example.com/education",
    order,
    isVisible: true,
  })),
  experiences: [0, 1, 2].map((order) => ({
    _id: `experience-${order}`,
    company: `Test Company ${order + 1}`,
    role: "Test Role",
    timeLabel: `202${order}.01 — 202${order}.12`,
    outcomes: ["Test outcome"],
    order,
    isVisible: true,
  })),
  capabilityGroups: [0, 1, 2, 3].map((order) => ({
    _id: `capability-${order}`,
    name: `Test Capability Group ${order + 1}`,
    items: ["Test capability"],
    order,
    isVisible: true,
  })),
  projects: [0, 1, 2].map((order) => ({
    _id: `project-${order}`,
    name: `Test Project ${order + 1}`,
    projectType: "Test Project Type",
    role: "Test Role",
    summary: "Test project summary.",
    outcomes: ["Test project outcome"],
    capabilities: ["Test capability"],
    order,
    isVisible: true,
  })),
  testimonials: [],
  socialLinks: [
    {_id: "social-email", platform: "email", label: "Email", url: "mailto:test@example.com", accessibilityLabel: "Email Test Person", order: 0, isVisible: true},
    {_id: "social-github", platform: "github", label: "GitHub", url: "https://github.com/example", accessibilityLabel: "Test GitHub profile", order: 1, isVisible: true},
    {_id: "social-linkedin", platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/in/example", accessibilityLabel: "Test LinkedIn profile", order: 2, isVisible: true},
  ],
  mediaRecords: [portrait, shareImage],
};
